services:
  frontend:
    build: ./Frontend
    ports:
      - "3001:5173"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./Backend
    expose:
      - "8000"
    networks:
      - default
      - dokploy-network
    environment:
      - MONGO_URI=mongodb://flipibook:Flipibook123@flipibook-database-y1m1gq:27017/?authSource=admin
      - EMAIL_USER=fistotech04@gmail.com
      - EMAIL_APP_PASSWORD=ghrn izix para kuyg
      - CLIENT_URL=https://flipibook.com
      - GATEWAY_PORT=8000
      - AUTH_PORT=5001
      - AUTH_SERVICE_PORT=5001
      - AUTH_SERVICE_URL=http://localhost:5001
    env_file:
      - path: ./Backend/.env
        required: false

networks:
  default:
    name: flipibook-flipibook-ts4dqs_default

  dokploy-network:
    name: dokploy-network
    external: true